import Foundation
import AppKit

// MARK: - Clipboard Operations
// Clipboard management logic for FreeFlow: transient clipboard markers (so
// clipboard managers ignore dictated text), smart leading/trailing spacing
// based on cursor context, and clipboard preservation/restore.
//
// Extracted from AppState to keep each feature modular and isolate changes
// that may be contributed upstream as separate pull requests.

extension AppState {

    // MARK: - Transient Clipboard Markers

    /// Standard pasteboard types that signal well-behaved clipboard managers
    /// (Maccy, Raycast, Paste, Clipy, Flycut, etc.) to skip recording the
    /// clipboard entry in their history.
    ///
    /// See: https://github.com/nicke5012/TransientPasteboardType
    ///
    /// These types are declared alongside `.string` when writing to the
    /// pasteboard. No app behavior changes \u2014 the text still pastes normally
    /// via Cmd-V \u2014 but clipboard managers that respect these conventions
    /// will not pollute the user's clipboard history with dictated text.
    static let transientClipboardTypes: [NSPasteboard.PasteboardType] = [
        NSPasteboard.PasteboardType("org.nspasteboard.TransientType"),
        NSPasteboard.PasteboardType("org.nspasteboard.ConcealedType"),
        NSPasteboard.PasteboardType("org.nspasteboard.AutoGeneratedType"),
        NSPasteboard.PasteboardType("de.petermaurer.TransientPasteboardType"),
    ]

    /// Declares the given text on the system pasteboard together with the
    /// standard transient type markers. Clipboard managers that respect
    /// TransientType / ConcealedType will ignore this entry.
    static func writeTransientString(_ text: String, to pasteboard: NSPasteboard) {
        let allTypes: [NSPasteboard.PasteboardType] = [.string] + transientClipboardTypes
        pasteboard.declareTypes(allTypes, owner: nil)
        pasteboard.setString(text, forType: .string)
        // Populate empty values for the marker types as required by some
        // clipboard systems that check the data rather than just the type.
        for type in transientClipboardTypes {
            pasteboard.setString("", forType: type)
        }
    }

    // MARK: - Smart Spacing

    // Characters after which we must NOT add a leading space (opening delimiters).
    // Includes ASCII and Unicode curly/smart variants of quotes and brackets.
    private static let openingDelimiters: Set<Character> = [
        "(", "[", "{",
        "\"",          // ASCII straight double-quote
        "\u{201C}",    // \u201c LEFT DOUBLE QUOTATION MARK (curly open)
        "'",           // ASCII straight single-quote / apostrophe
        "\u{2018}",    // \u2018 LEFT SINGLE QUOTATION MARK (curly open)
        "`", "<", "\u{00AB}",
        "\u{2039}",    // \u2039 SINGLE LEFT-POINTING ANGLE QUOTATION MARK
    ]

    // Characters that, when appearing at the START of a transcript, mean we
    // should NOT prepend a space (it's punctuation or a closing delimiter).
    private static let leadingPunctuation: Set<Character> = [
        ".", ",", ";", ":", "!", "?",
        ")", "]", "}",
        "\"", "\u{201D}",  // \u201d RIGHT DOUBLE QUOTATION MARK (curly close)
        "'", "\u{2019}",   // \u2019 RIGHT SINGLE QUOTATION MARK / apostrophe
        ">", "\u{00BB}", "\u{203A}",  // \u203a SINGLE RIGHT-POINTING ANGLE QUOTATION MARK
        "\u{2026}",
    ]

    // Terminal punctuation that closes a sentence. After these, we do NOT
    // append a trailing space \u2014 the sentence is finished.
    private static let terminalPunctuation: Set<Character> = [".", "!", "?", "\u{2026}"]

    /// Computes the leading space needed before the transcript based on the
    /// text preceding the cursor. Returns the transcript with a prepended
    /// space if word separation is needed.
    ///
    /// Skips adding space when:
    ///   - `cursorPosition` is `"start"` (cursor at start of field or new paragraph)
    ///   - `precedingText` ends with whitespace, newline, or an opening delimiter
    ///   - transcript starts with whitespace, newline, or punctuation
    ///   - the last non-space character of `precedingText` is a newline, which
    ///     signals the cursor is at the beginning of a new paragraph even when
    ///     the Accessibility API omits the trailing `\n`
    static func applySmartLeadingSpace(
        _ transcript: String,
        precedingText: String?,
        cursorPosition: String? = nil
    ) -> String {
        // Cursor is explicitly at the start of a field \u2014 never add a leading space.
        if cursorPosition == "start" { return transcript }

        guard let preceding = precedingText,
              let firstChar = transcript.first else {
            return transcript
        }

        // Detect new paragraph: find the last non-space character in preceding text.
        // If it is a newline, the cursor is at the beginning of a new line \u2014 no space needed.
        let lastNonSpace = preceding.reversed().first(where: { !($0 == " " || $0 == "\t") })
        if let c = lastNonSpace, c.isNewline { return transcript }

        guard let lastChar = preceding.last else { return transcript }

        let needsLeadingSpace = !lastChar.isWhitespace
            && !lastChar.isNewline
            && !openingDelimiters.contains(lastChar)
            && !firstChar.isWhitespace
            && !firstChar.isNewline
            && !leadingPunctuation.contains(firstChar)
        return needsLeadingSpace ? " " + transcript : transcript
    }

    /// Computes the trailing space needed after the transcript based on the
    /// text following the cursor. Returns the transcript with an appended
    /// space if word separation is needed.
    ///
    /// - At end of field (no followingText): NEVER adds a trailing space.
    ///   The user prefers dictations to end cleanly without trailing whitespace.
    ///   Consecutive dictations are handled by `applySmartLeadingSpace`.
    /// - When followingText exists: adds a space ONLY if the following text
    ///   is a letter/number (not punctuation or existing whitespace).
    static func applySmartTrailingSpace(
        _ rawTranscript: String,
        followingText: String?
    ) -> String {
        // Strip any trailing whitespace from the transcript before computing
        // spacing. This acts as a catch-all safety net: regardless of whether
        // the LLM, the formatting rules, or the Accessibility API introduced
        // a trailing space, the pasted text will never end with stray whitespace.
        var transcript = rawTranscript
        while let lastChar = transcript.last, lastChar.isWhitespace {
            transcript.removeLast()
        }

        guard let lastChar = transcript.last else {
            return transcript
        }

        // --- Case 1: No following text (cursor at end of field) ---
        // Never append a trailing space at the end of a field.
        // If the user dictates again, `applySmartLeadingSpace` will prepend
        // the necessary space based on the preceding character.
        guard let following = followingText, !following.isEmpty else {
            return transcript
        }

        // --- Case 2: Following text exists ---
        let firstFollowingChar = following.first!
        let followingStartsWithSpace = firstFollowingChar.isWhitespace || firstFollowingChar.isNewline

        // If following text already starts with space/newline, no space needed
        guard !followingStartsWithSpace else {
            return transcript
        }

        let firstFollowingNonWS = following.first(where: { !$0.isWhitespace && !$0.isNewline })
        let followingHasPunctNext = firstFollowingNonWS.map { leadingPunctuation.contains($0) } ?? false

        // If following text starts with punctuation, no space needed
        guard !followingHasPunctNext else {
            return transcript
        }

        // Following text starts with a letter/digit \u2014 we need separation.
        // E.g. inserting "word" before "another" -> "word another"
        let needsTrailingSpace = !lastChar.isWhitespace
            && !lastChar.isNewline
            && !openingDelimiters.contains(lastChar)
        return needsTrailingSpace ? transcript + " " : transcript
    }
}
